### ISSUE TITLE
Error calling RPC method GetBlueprints: ReferenceError: File is not defined

### ISSUE THREAD

**Issue by runtimevic** [Mobject-Dev-Team/mobject-graph-webserver#1]
Hello @benhar-dev ,
Error calling RPC method GetBlueprints: ReferenceError: File is not defined...
- I don't know why I get this error..
- It is possible to add in the readme.md how to test it...
- It is possible to attach the TwinCAT 3 project to the repository..., if needed to test it..

thanks you, Víctor.

![mobject-graph-webserver](https://github.com/Mobject-Dev-Team/mobject-graph-webserver/assets/53791834/cc31ca01-72fa-473a-bc49-b833494823b4)

**Comment by benhar-dev** [comment]
Hi @runtimevic, currently the mobject-graph TwinCAT library and test-project is not public, we will be releasing this in the very near future once there is documentation and "how to" videos available.
